# Generated by Django 5.0.6 on 2024-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_remove_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20, verbose_name='전화번호'),
        ),
    ]
