# Generated by Django 5.0.6 on 2024-07-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='alertDateTime',
            new_name='alert_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='clubMember',
            new_name='club_member',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='endDateTime',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventId',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventTitle',
            new_name='event_title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='gameMode',
            new_name='game_mode',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='repeatType',
            new_name='repeat_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDateTime',
            new_name='start_date_time',
        ),
    ]
