# Generated by Django 4.2.14 on 2024-08-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_alter_clubmember_total_avg_score_and_more"),
        ("events", "0004_event_team_a_group_wins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="clubs.club",
            ),
        ),
    ]
