# Generated by Django 4.2.14 on 2024-10-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="site",
            field=models.CharField(
                default="unknown_site", max_length=255, verbose_name="장소명"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                default="unknown_location", max_length=255, verbose_name="위도/경도"
            ),
        ),
    ]
