# Generated by Django 4.2.14 on 2025-07-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("golf_data", "0003_alter_tee_tee_name"),
        ("events", "0006_event_site_alter_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="golf_club_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="golf_data.golfclub",
                verbose_name="골프장",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="golf_course_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="golf_data.golfcourse",
                verbose_name="골프 코스",
            ),
        ),
    ]
