# Generated by Django 4.2.14 on 2025-07-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("golf_data", "0003_alter_tee_tee_name"),
        ("events", "0007_event_golf_club_id_event_golf_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="golf_course_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="golf_data.golfcourse",
                verbose_name="골프 코스",
            ),
        ),
    ]
