# Generated by Django 5.0.6 on 2024-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_userid_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handicap',
            field=models.IntegerField(default='0', verbose_name='핸디캡'),
        ),
    ]
