# Generated by Django 4.2.14 on 2024-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="handicap",
            field=models.IntegerField(default=0, verbose_name="핸디캡"),
        ),
    ]
