# Generated by Django 4.2.14 on 2024-12-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
    ]
