# Generated by Django 4.2.14 on 2025-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="0000000000",
                max_length=20,
                null=True,
                verbose_name="전화번호",
            ),
        ),
    ]
