# Generated by Django 4.2.22 on 2025-08-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_accepted_terms",
            field=models.BooleanField(default=True, verbose_name="약관 동의 여부"),
        ),
        migrations.AddField(
            model_name="user",
            name="has_basic_info",
            field=models.BooleanField(default=True, verbose_name="기본 정보 입력 여부"),
        ),
        migrations.AddField(
            model_name="user",
            name="has_profile_image",
            field=models.BooleanField(
                default=False, verbose_name="프로필 이미지 업로드 여부"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_info_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="마지막 정보 수정일"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("basic_info", "Basic Info"),
                    ("terms_accepted", "Terms Accepted"),
                    ("profile_complete", "Profile Complete"),
                    ("active", "Active"),
                ],
                default="active",
                max_length=20,
                verbose_name="등록 상태",
            ),
        ),
    ]
