# Generated by Django 4.2.22 on 2025-08-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_add_user_registration_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_accepted_terms",
        ),
        migrations.RemoveField(
            model_name="user",
            name="has_basic_info",
        ),
        migrations.RemoveField(
            model_name="user",
            name="has_profile_image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_info_update",
        ),
        migrations.RemoveField(
            model_name="user",
            name="registration_status",
        ),
    ]
