# Generated by Django 4.2.14 on 2024-12-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(verbose_name="피드백 내용"),
        ),
    ]
