# Generated by Django 5.0.6 on 2024-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='unknown_user', max_length=150, unique=True, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('login_type', models.CharField(choices=[('general', 'General'), ('social', 'Social')], default='general', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(default='Unknown', max_length=128, verbose_name='이름')),
                ('phone_number', models.CharField(default='000-000-0000', max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('handicap', models.CharField(default='0', max_length=20, verbose_name='핸디캡')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='학번')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='계정 수정일')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='최근 접속일')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
