# Generated by Django 5.0.6 on 2024-06-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, null=True, verbose_name='비밀번호'),
        ),
    ]
