# Generated by Django 4.2.14 on 2024-08-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_handicap"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="accounts/", verbose_name="프로필 사진"
            ),
        ),
    ]
