# Generated by Django 4.2.14 on 2024-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_handicap"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="FCM 토큰 저장 필드"
            ),
        ),
    ]
