# Generated by Django 4.2.14 on 2024-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_fcm_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="handicap",
            field=models.IntegerField(default=30, verbose_name="핸디캡"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="0000000000", max_length=20, verbose_name="전화번호"
            ),
        ),
    ]
