# Generated by Django 5.0.6 on 2024-07-26 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0002_alter_clubmember_role'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.CharField(choices=[('NONE', 'None'), ('A', 'Team A'), ('B', 'Team B')], default='NONE', max_length=6, verbose_name='팀 타입')),
                ('group_type', models.IntegerField(choices=[(1, '1조'), (2, '2조'), (3, '3조'), (4, '4조'), (5, '5조'), (6, '6조'), (7, '7조'), (8, '8조')], verbose_name='조 타입')),
                ('status_type', models.CharField(choices=[('PARTY', '수락 및 회식'), ('ACCEPT', '수락'), ('DENY', '거절'), ('PENDING', '대기')], default='PENDING', max_length=7, verbose_name='상태')),
                ('sum_score', models.IntegerField(default=0, verbose_name='총 점수')),
                ('rank', models.IntegerField(default=0, verbose_name='랭킹')),
                ('club_member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.clubmember')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
