# Generated by Django 5.0.6 on 2024-08-01 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_holescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holescore',
            name='event',
        ),
    ]
