# Generated by Django 4.2.14 on 2024-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0005_participant_handicap_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="rank",
            field=models.CharField(
                blank=True, default="0", max_length=10, null=True, verbose_name="랭킹"
            ),
        ),
    ]
