# Generated by Django 4.2.14 on 2024-08-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0006_alter_participant_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="is_group_win",
            field=models.BooleanField(
                default=False, verbose_name="속한 조에서 승리 여부"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="is_group_win_handicap",
            field=models.BooleanField(
                default=False, verbose_name="속한 조에서 핸디캡 승리 여부"
            ),
        ),
    ]
