# Generated by Django 4.2.14 on 2024-08-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0008_participant_handicap_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="points",
            field=models.IntegerField(default=0, verbose_name="포인트"),
        ),
    ]
