# Generated by Django 4.2.14 on 2024-08-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0009_participant_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="points",
        ),
    ]
