# Generated by Django 4.2.22 on 2025-09-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0011_participant_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="holescore",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
