# Generated by Django 5.0.6 on 2024-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status_type',
            field=models.CharField(choices=[('PARTY', '수락 및 회식'), ('ACCEPT', '수락'), ('DENY', '거절'), ('PENDING', '대기')], default='PENDING', max_length=7, verbose_name='상태'),
        ),
    ]
