# Generated by Django 5.0.6 on 2024-07-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='handicap',
        ),
    ]
