# Generated by Django 4.2.14 on 2024-08-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0007_participant_is_group_win_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="handicap_rank",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=10,
                null=True,
                verbose_name="핸디캡 랭킹",
            ),
        ),
    ]
