# Generated by Django 4.2.14 on 2024-10-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GolfClub",
            fields=[
                (
                    "facility_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "club_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="club name"
                    ),
                ),
                ("address", models.TextField(verbose_name="address")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "golf_clubs",
            },
        ),
        migrations.CreateModel(
            name="GolfCourse",
            fields=[
                (
                    "course_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "course_name",
                    models.CharField(max_length=255, verbose_name="course name"),
                ),
                (
                    "holes",
                    models.PositiveIntegerField(default=18, verbose_name="holes"),
                ),
                ("par", models.PositiveIntegerField(default=72, verbose_name="par")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="golf_data.golfclub",
                    ),
                ),
            ],
            options={
                "db_table": "golf_courses",
                "unique_together": {("club", "course_name")},
            },
        ),
        migrations.CreateModel(
            name="Tee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hole_1_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole1 Par"),
                ),
                (
                    "hole_2_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole2 Par"),
                ),
                (
                    "hole_3_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole3 Par"),
                ),
                (
                    "hole_4_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole4 Par"),
                ),
                (
                    "hole_5_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole5 Par"),
                ),
                (
                    "hole_6_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole6 Par"),
                ),
                (
                    "hole_7_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole7 Par"),
                ),
                (
                    "hole_8_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole8 Par"),
                ),
                (
                    "hole_9_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole9 Par"),
                ),
                (
                    "hole_10_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole10 Par"),
                ),
                (
                    "hole_11_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole11 Par"),
                ),
                (
                    "hole_12_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole12 Par"),
                ),
                (
                    "hole_13_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole13 Par"),
                ),
                (
                    "hole_14_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole14 Par"),
                ),
                (
                    "hole_15_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole15 Par"),
                ),
                (
                    "hole_16_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole16 Par"),
                ),
                (
                    "hole_17_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole17 Par"),
                ),
                (
                    "hole_18_par",
                    models.PositiveIntegerField(default=0, verbose_name="Hole18 Par"),
                ),
                (
                    "hole_1_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole1 Handicap"
                    ),
                ),
                (
                    "hole_2_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole2 Handicap"
                    ),
                ),
                (
                    "hole_3_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole3 Handicap"
                    ),
                ),
                (
                    "hole_4_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole4 Handicap"
                    ),
                ),
                (
                    "hole_5_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole5 Handicap"
                    ),
                ),
                (
                    "hole_6_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole6 Handicap"
                    ),
                ),
                (
                    "hole_7_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole7 Handicap"
                    ),
                ),
                (
                    "hole_8_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole8 Handicap"
                    ),
                ),
                (
                    "hole_9_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole9 Handicap"
                    ),
                ),
                (
                    "hole_10_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole10 Handicap"
                    ),
                ),
                (
                    "hole_11_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole11 Handicap"
                    ),
                ),
                (
                    "hole_12_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole12 Handicap"
                    ),
                ),
                (
                    "hole_13_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole13 Handicap"
                    ),
                ),
                (
                    "hole_14_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole14 Handicap"
                    ),
                ),
                (
                    "hole_15_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole15 Handicap"
                    ),
                ),
                (
                    "hole_16_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole16 Handicap"
                    ),
                ),
                (
                    "hole_17_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole17 Handicap"
                    ),
                ),
                (
                    "hole_18_handicap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hole18 Handicap"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tees",
                        to="golf_data.golfcourse",
                    ),
                ),
            ],
            options={
                "db_table": "golf_tees",
            },
        ),
    ]
