# Generated by Django 4.2.14 on 2025-03-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelFileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="golf_data/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "excel_file_uploads",
            },
        ),
        migrations.CreateModel(
            name="GolfClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="club name"
                    ),
                ),
                ("address", models.TextField(verbose_name="address")),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "golf_clubs",
            },
        ),
        migrations.CreateModel(
            name="GolfCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=255, verbose_name="course name"),
                ),
                (
                    "holes",
                    models.PositiveIntegerField(default=18, verbose_name="holes"),
                ),
                ("par", models.PositiveIntegerField(default=72, verbose_name="par")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="golf_data.golfclub",
                    ),
                ),
            ],
            options={
                "db_table": "golf_courses",
                "unique_together": {("club", "course_name")},
            },
        ),
        migrations.CreateModel(
            name="Tee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tee_name", models.CharField(max_length=50, verbose_name="tee name")),
                (
                    "hole_1_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole1 Par"
                    ),
                ),
                (
                    "hole_2_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole2 Par"
                    ),
                ),
                (
                    "hole_3_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole3 Par"
                    ),
                ),
                (
                    "hole_4_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole4 Par"
                    ),
                ),
                (
                    "hole_5_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole5 Par"
                    ),
                ),
                (
                    "hole_6_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole6 Par"
                    ),
                ),
                (
                    "hole_7_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole7 Par"
                    ),
                ),
                (
                    "hole_8_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole8 Par"
                    ),
                ),
                (
                    "hole_9_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole9 Par"
                    ),
                ),
                (
                    "hole_10_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole10 Par"
                    ),
                ),
                (
                    "hole_11_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole11 Par"
                    ),
                ),
                (
                    "hole_12_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole12 Par"
                    ),
                ),
                (
                    "hole_13_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole13 Par"
                    ),
                ),
                (
                    "hole_14_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole14 Par"
                    ),
                ),
                (
                    "hole_15_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole15 Par"
                    ),
                ),
                (
                    "hole_16_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole16 Par"
                    ),
                ),
                (
                    "hole_17_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole17 Par"
                    ),
                ),
                (
                    "hole_18_par",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole18 Par"
                    ),
                ),
                (
                    "hole_1_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole1 Handicap"
                    ),
                ),
                (
                    "hole_2_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole2 Handicap"
                    ),
                ),
                (
                    "hole_3_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole3 Handicap"
                    ),
                ),
                (
                    "hole_4_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole4 Handicap"
                    ),
                ),
                (
                    "hole_5_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole5 Handicap"
                    ),
                ),
                (
                    "hole_6_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole6 Handicap"
                    ),
                ),
                (
                    "hole_7_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole7 Handicap"
                    ),
                ),
                (
                    "hole_8_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole8 Handicap"
                    ),
                ),
                (
                    "hole_9_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole9 Handicap"
                    ),
                ),
                (
                    "hole_10_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole10 Handicap"
                    ),
                ),
                (
                    "hole_11_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole11 Handicap"
                    ),
                ),
                (
                    "hole_12_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole12 Handicap"
                    ),
                ),
                (
                    "hole_13_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole13 Handicap"
                    ),
                ),
                (
                    "hole_14_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole14 Handicap"
                    ),
                ),
                (
                    "hole_15_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole15 Handicap"
                    ),
                ),
                (
                    "hole_16_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole16 Handicap"
                    ),
                ),
                (
                    "hole_17_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole17 Handicap"
                    ),
                ),
                (
                    "hole_18_handicap",
                    models.CharField(
                        default="0", max_length=10, verbose_name="Hole18 Handicap"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tees",
                        to="golf_data.golfcourse",
                    ),
                ),
            ],
            options={
                "db_table": "golf_tees",
                "unique_together": {("course", "tee_name")},
            },
        ),
    ]
