# Generated by Django 4.2.14 on 2025-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfclub",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="golfclub",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
    ]
