# Generated by Django 4.2.14 on 2024-10-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelFileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="golf_data/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "excel_file_uploads",
            },
        ),
    ]
