# Generated by Django 4.2.14 on 2025-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf_data", "0002_alter_tee_hole_10_handicap_alter_tee_hole_10_par_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tee",
            name="tee_name",
            field=models.CharField(max_length=255, verbose_name="tee name"),
        ),
    ]
