# Generated by Django 5.0.6 on 2024-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(choices=[('member', 'M'), ('admin', 'A')], default='member', max_length=10),
        ),
    ]
