# Generated by Django 4.2.14 on 2024-08-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_clubmember_total_handicap_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clubmember",
            old_name="total_sum_score",
            new_name="total_avg_score",
        ),
        migrations.RenameField(
            model_name="clubmember",
            old_name="total_handicap_score",
            new_name="total_handicap_avg_score",
        ),
    ]
