# Generated by Django 4.2.22 on 2025-09-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_alter_clubmember_total_avg_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("pending", "초대 수락 대기"),
                    ("active", "정상 멤버"),
                    ("banned", "차단"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
