# Generated by Django 4.2.22 on 2025-09-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0010_alter_clubmember_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmember",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("invited", "초대됨"),
                    ("applied", "가입신청"),
                    ("active", "활성"),
                    ("rejected", "거절됨"),
                    ("banned", "차단됨"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
