# Generated by Django 4.2.14 on 2024-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_event_club_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="group_win_team",
            field=models.CharField(
                choices=[
                    ("NONE", "결과 없음"),
                    ("A", "Team A"),
                    ("B", "Team B"),
                    ("DRAW", "무승부"),
                ],
                default="NONE",
                max_length=4,
                verbose_name="승리 팀 by 조",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="group_win_team_handicap",
            field=models.CharField(
                choices=[
                    ("NONE", "결과 없음"),
                    ("A", "Team A"),
                    ("B", "Team B"),
                    ("DRAW", "무승부"),
                ],
                default="NONE",
                max_length=4,
                verbose_name="승리 팀 by 핸디캡 조",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="total_win_team",
            field=models.CharField(
                choices=[
                    ("NONE", "결과 없음"),
                    ("A", "Team A"),
                    ("B", "Team B"),
                    ("DRAW", "무승부"),
                ],
                default="NONE",
                max_length=4,
                verbose_name="승리 팀 by 합계",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="total_win_team_handicap",
            field=models.CharField(
                choices=[
                    ("NONE", "결과 없음"),
                    ("A", "Team A"),
                    ("B", "Team B"),
                    ("DRAW", "무승부"),
                ],
                default="NONE",
                max_length=4,
                verbose_name="승리 팀 by 핸디캡 합계",
            ),
        ),
    ]
