# Generated by Django 4.2.14 on 2024-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_group_win_team_event_group_win_team_handicap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="team_a_group_wins",
            field=models.IntegerField(default=0, verbose_name="Team A 조별 승리 수"),
        ),
        migrations.AddField(
            model_name="event",
            name="team_a_group_wins_handicap",
            field=models.IntegerField(
                default=0, verbose_name="Team A 핸디캡 적용한 조별 승리 수"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="team_a_total_score",
            field=models.IntegerField(default=0, verbose_name="Team A 전체 점수 합계"),
        ),
        migrations.AddField(
            model_name="event",
            name="team_a_total_score_handicap",
            field=models.IntegerField(
                default=0, verbose_name="Team A 핸디캡 적용한 전체 점수 합계"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="team_b_group_wins",
            field=models.IntegerField(default=0, verbose_name="Team B 조별 승리 수"),
        ),
        migrations.AddField(
            model_name="event",
            name="team_b_group_wins_handicap",
            field=models.IntegerField(
                default=0, verbose_name="Team B 핸디캡 적용한 조별 승리 수"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="team_b_total_score",
            field=models.IntegerField(default=0, verbose_name="Team B 전체 점수 합계"),
        ),
        migrations.AddField(
            model_name="event",
            name="team_b_total_score_handicap",
            field=models.IntegerField(
                default=0, verbose_name="Team B 핸디캡 적용한 전체 점수 합계"
            ),
        ),
    ]
