# Generated by Django 4.2.14 on 2025-07-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_event_golf_course_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="golf_club_id",
            new_name="golf_club",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="golf_course_id",
            new_name="golf_course",
        ),
    ]
