# Generated by Django 4.2.14 on 2025-07-04 10:40

from django.db import migrations

def forwards(apps, schema_editor):
    Event      = apps.get_model('events', 'Event')
    GolfClub   = apps.get_model('golf_data', 'GolfClub')
    GolfCourse = apps.get_model('golf_data', 'GolfCourse')

    for ev in Event.objects.all():
        club = GolfClub.objects.filter(club_name=ev.site).first()
        if club:
            ev.golf_club   = club
            first_course  = club.courses.first()
            ev.golf_course = first_course if first_course else None
        else:
            ev.golf_club   = None
            ev.golf_course = None

        ev.save(update_fields=['golf_club', 'golf_course'])

def reverse(apps, schema_editor):
    # 롤백 시 특별 처리 필요 없다면 pass
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_golf_club_id_event_golf_club_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
