# Generated by Django 4.2.22 on 2025-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_migrate_site_to_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="opening_commentary_played",
            field=models.BooleanField(
                default=False, verbose_name="오프닝 해설 재생 여부"
            ),
        ),
    ]
