# Generated by Django 4.2.22 on 2025-09-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_event_opening_commentary_played"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="opening_commentary_played",
        ),
    ]
