# Generated by Django 4.2.14 on 2024-08-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_alter_clubmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="total_handicap_rank",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=10,
                null=True,
                verbose_name="모임 내 전체 핸디캡 랭킹",
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="total_points",
            field=models.IntegerField(default=0, verbose_name="전체 포인트"),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="total_rank",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=10,
                null=True,
                verbose_name="모임 내 전체 랭킹",
            ),
        ),
    ]
