# Generated by Django 4.2.14 on 2024-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_remove_clubmember_total_handicap_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="total_handicap_rank",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=10,
                null=True,
                verbose_name="모임 내 전체 핸디캡 적용 랭킹",
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="total_rank",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=10,
                null=True,
                verbose_name="모임 내 전체 랭킹",
            ),
        ),
    ]
