# Generated by Django 4.2.14 on 2024-08-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_clubmember_total_handicap_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="total_handicap_score",
            field=models.IntegerField(
                default=0, verbose_name="모임 내 이벤트의 핸디캡 적용 스코어 총합"
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="total_sum_score",
            field=models.IntegerField(
                default=0, verbose_name="모임 내 이벤트의 스코어 총합"
            ),
        ),
    ]
