# Generated by Django 4.2.14 on 2024-08-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_rename_total_sum_score_clubmember_total_avg_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmember",
            name="total_avg_score",
            field=models.FloatField(
                default=0.0, verbose_name="모임 내 모든 이벤트의 평균 점수"
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="total_handicap_avg_score",
            field=models.FloatField(
                default=0.0, verbose_name="모임 내 모든 이벤트의 핸디캡 적용 평균 점수"
            ),
        ),
    ]
