# Generated by Django 5.0.6 on 2024-07-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('club_member_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
