# Generated by Django 5.0.6 on 2024-07-23 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubMembers', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmember',
            name='club_member_name',
        ),
        migrations.AddField(
            model_name='clubmember',
            name='member',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
            preserve_default=False,
        ),
    ]
