# Generated by Django 5.0.6 on 2024-07-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubMembers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmember',
            old_name='clubMemberId',
            new_name='club_member_id',
        ),
    ]
