# Generated by Django 4.2.14 on 2025-03-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tee",
            name="hole_10_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole10 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_10_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole10 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_11_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole11 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_11_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole11 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_12_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole12 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_12_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole12 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_13_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole13 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_13_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole13 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_14_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole14 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_14_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole14 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_15_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole15 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_15_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole15 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_16_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole16 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_16_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole16 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_17_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole17 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_17_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole17 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_18_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole18 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_18_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole18 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_1_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole1 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_1_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole1 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_2_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole2 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_2_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole2 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_3_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole3 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_3_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole3 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_4_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole4 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_4_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole4 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_5_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole5 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_5_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole5 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_6_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole6 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_6_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole6 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_7_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole7 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_7_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole7 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_8_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole8 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_8_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole8 Par"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_9_handicap",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole9 Handicap"
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="hole_9_par",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Hole9 Par"
            ),
        ),
    ]
