# Generated by Django 4.2.22 on 2025-08-30 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connection_id",
                    models.CharField(max_length=255, verbose_name="연결 ID"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="사용자 에이전트"
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="연결 시간"
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="연결 해제 시간"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 연결 여부"),
                ),
            ],
            options={
                "verbose_name": "채팅 연결",
                "verbose_name_plural": "채팅 연결들",
                "db_table": "chat_connections",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "텍스트"),
                            ("IMAGE", "이미지"),
                            ("SYSTEM", "시스템 메시지"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="메시지 타입",
                    ),
                ),
                ("content", models.TextField(verbose_name="메시지 내용")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="전송일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지들",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chat_room_name",
                    models.CharField(max_length=200, verbose_name="채팅방 이름"),
                ),
                (
                    "chat_room_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "이벤트 채팅방"),
                            ("CLUB", "클럽 채팅방"),
                            ("GLOBAL", "전체 채팅방"),
                        ],
                        max_length=20,
                        verbose_name="채팅방 타입",
                    ),
                ),
                (
                    "event_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="이벤트 ID"
                    ),
                ),
                (
                    "club_id",
                    models.IntegerField(blank=True, null=True, verbose_name="클럽 ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
            ],
            options={
                "verbose_name": "채팅방",
                "verbose_name_plural": "채팅방들",
                "db_table": "chat_rooms",
            },
        ),
        migrations.CreateModel(
            name="ChatRoomParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MEMBER", "일반 멤버"),
                            ("ADMIN", "관리자"),
                            ("MODERATOR", "운영자"),
                        ],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="참여일"
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 읽은 시간"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.chatroom",
                        verbose_name="채팅방",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅방 참가자",
                "verbose_name_plural": "채팅방 참가자들",
                "db_table": "chat_room_participants",
            },
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["chat_room_type", "event_id"],
                name="chat_rooms_chat_ro_82fe01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["chat_room_type", "club_id"],
                name="chat_rooms_chat_ro_0ce9c2_idx",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chat_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatroom",
                verbose_name="채팅방",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="발신자",
            ),
        ),
        migrations.AddField(
            model_name="chatconnection",
            name="chat_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="chat.chatroom",
                verbose_name="채팅방",
            ),
        ),
        migrations.AddField(
            model_name="chatconnection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_connections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroomparticipant",
            index=models.Index(
                fields=["chat_room", "is_active"], name="chat_room_p_chat_ro_42b2eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroomparticipant",
            index=models.Index(
                fields=["user", "is_active"], name="chat_room_p_user_id_4dfc10_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroomparticipant",
            unique_together={("chat_room", "user")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat_room", "created_at"],
                name="chat_messag_chat_ro_b6bf60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="chat_messag_sender__7a605a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconnection",
            index=models.Index(
                fields=["user", "is_active"], name="chat_connec_user_id_c9047c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconnection",
            index=models.Index(
                fields=["chat_room", "is_active"], name="chat_connec_chat_ro_58da65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconnection",
            index=models.Index(
                fields=["connected_at"], name="chat_connec_connect_4200b3_idx"
            ),
        ),
    ]
