# Generated by Django 4.2.22 on 2025-09-05 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_announcement",
            field=models.BooleanField(default=False, verbose_name="공지 여부"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="고정 여부"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="우선순위"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "텍스트"),
                    ("IMAGE", "이미지"),
                    ("SYSTEM", "시스템 메시지"),
                    ("ANNOUNCEMENT", "공지 메시지"),
                    ("ADMIN", "관리자 메시지"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="메시지 타입",
            ),
        ),
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="읽은 시간"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=True, verbose_name="읽음 여부"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_statuses",
                        to="chat.chatmessage",
                        verbose_name="메시지",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "메시지 읽음 상태",
                "verbose_name_plural": "메시지 읽음 상태들",
                "db_table": "message_read_statuses",
                "indexes": [
                    models.Index(
                        fields=["message", "is_read"],
                        name="message_rea_message_60b2f6_idx",
                    ),
                    models.Index(
                        fields=["user", "read_at"],
                        name="message_rea_user_id_38e360_idx",
                    ),
                ],
                "unique_together": {("message", "user")},
            },
        ),
        migrations.CreateModel(
            name="ChatReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("👍", "좋아요"),
                            ("❤️", "하트"),
                            ("😂", "웃음"),
                            ("😮", "놀람"),
                            ("😢", "슬픔"),
                            ("😡", "화남"),
                        ],
                        max_length=10,
                        verbose_name="반응",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chat.chatmessage",
                        verbose_name="메시지",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "메시지 반응",
                "verbose_name_plural": "메시지 반응들",
                "db_table": "chat_reactions",
                "indexes": [
                    models.Index(
                        fields=["message", "reaction"],
                        name="chat_reacti_message_5a9d88_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="chat_reacti_user_id_9c626f_idx",
                    ),
                ],
                "unique_together": {("message", "user", "reaction")},
            },
        ),
        migrations.CreateModel(
            name="ChatNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "새 메시지"),
                            ("ANNOUNCEMENT", "공지사항"),
                            ("MENTION", "멘션"),
                            ("REACTION", "반응"),
                            ("ADMIN", "관리자 메시지"),
                        ],
                        default="MESSAGE",
                        max_length=20,
                        verbose_name="알림 타입",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="알림 제목")),
                ("content", models.TextField(verbose_name="알림 내용")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="chat.chatroom",
                        verbose_name="채팅방",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="chat.chatmessage",
                        verbose_name="메시지",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 알림",
                "verbose_name_plural": "채팅 알림들",
                "db_table": "chat_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="chat_notifi_user_id_d62bb8_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "created_at"],
                        name="chat_notifi_chat_ro_7f1e09_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="chat_notifi_notific_eb2ccf_idx",
                    ),
                ],
            },
        ),
    ]
