# Generated by Django 4.2.22 on 2025-09-07 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_migrate_site_to_fk"),
        ("chat", "0002_chatmessage_is_announcement_chatmessage_is_pinned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "player_name",
                    models.CharField(max_length=100, verbose_name="선수 이름"),
                ),
                ("hole_number", models.IntegerField(verbose_name="홀 번호")),
                ("par", models.IntegerField(verbose_name="파")),
                ("score", models.IntegerField(verbose_name="타수")),
                ("score_relative_to_par", models.IntegerField(verbose_name="파대비")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="처리 완료"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="이벤트",
                    ),
                ),
            ],
            options={
                "verbose_name": "임시 점수",
                "verbose_name_plural": "임시 점수들",
                "db_table": "chat_pending_scores",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "processed"],
                        name="chat_pendin_event_i_709cc8_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="chat_pendin_created_7b44ec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BroadcastCommentary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "broadcast_type",
                    models.CharField(
                        choices=[
                            ("opening", "오프닝"),
                            ("score_update", "점수 업데이트"),
                            ("player_highlight", "선수 하이라이트"),
                            ("chat_interaction", "채팅 상호작용"),
                            ("closing", "클로징"),
                            ("batch_update", "배치 업데이트"),
                        ],
                        max_length=20,
                        verbose_name="방송 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="방송 내용")),
                (
                    "related_hole",
                    models.IntegerField(blank=True, null=True, verbose_name="관련 홀"),
                ),
                (
                    "related_player",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="관련 플레이어",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_commentaries",
                        to="events.event",
                        verbose_name="이벤트",
                    ),
                ),
            ],
            options={
                "verbose_name": "중계방송 텍스트",
                "verbose_name_plural": "중계방송 텍스트들",
                "db_table": "chat_broadcast_commentaries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "broadcast_type"],
                        name="chat_broadc_event_i_edfd43_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="chat_broadc_created_5dcbed_idx"
                    ),
                ],
            },
        ),
    ]
