# Generated by Django 4.2.22 on 2025-09-07 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_pendingscore_broadcastcommentary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingscore",
            name="event",
        ),
        migrations.DeleteModel(
            name="BroadcastCommentary",
        ),
        migrations.DeleteModel(
            name="PendingScore",
        ),
    ]
