# Generated by Django 4.2.22 on 2025-09-14 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_remove_pendingscore_event_delete_broadcastcommentary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="차단 사유"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="차단일"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "blocked_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="차단된 사용자",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="차단한 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 차단",
                "verbose_name_plural": "사용자 차단들",
                "db_table": "user_blocks",
                "indexes": [
                    models.Index(
                        fields=["blocker", "is_active"],
                        name="user_blocks_blocker_509862_idx",
                    ),
                    models.Index(
                        fields=["blocked_user", "is_active"],
                        name="user_blocks_blocked_2253eb_idx",
                    ),
                ],
                "unique_together": {("blocker", "blocked_user")},
            },
        ),
        migrations.CreateModel(
            name="ChatReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SPAM", "스팸 또는 광고"),
                            ("ABUSE", "욕설 또는 비하"),
                            ("INAPPROPRIATE", "부적절한 내용"),
                            ("PRIVACY", "개인정보 유출"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="신고 유형",
                    ),
                ),
                ("reason", models.TextField(verbose_name="신고 사유")),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="상세 내용"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("REVIEWING", "검토중"),
                            ("RESOLVED", "해결됨"),
                            ("DISMISSED", "기각됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="신고일"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="처리일"),
                ),
                (
                    "reported_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="chat.chatmessage",
                        verbose_name="신고된 메시지",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고된 사용자",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 신고",
                "verbose_name_plural": "채팅 신고들",
                "db_table": "chat_reports",
                "indexes": [
                    models.Index(
                        fields=["reported_user", "status"],
                        name="chat_report_reporte_2214f3_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="chat_report_status_1c6d34_idx",
                    ),
                ],
            },
        ),
    ]
