# Generated by Django 4.2.22 on 2025-09-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_userblock_chatreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sender_profile_image",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="발신자 프로필 이미지 URL",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender_unique_id",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="발신자 고유 ID"
            ),
        ),
    ]
