# Generated by Django 4.2.22 on 2025-09-27 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0006_chatmessage_sender_profile_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="알림 활성화"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="chat.chatroom",
                        verbose_name="채팅방",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 알림 설정",
                "verbose_name_plural": "채팅 알림 설정들",
                "db_table": "chat_notification_settings",
                "indexes": [
                    models.Index(
                        fields=["user", "chat_room"],
                        name="chat_notifi_user_id_f08fbc_idx",
                    ),
                    models.Index(
                        fields=["is_enabled"], name="chat_notifi_is_enab_855392_idx"
                    ),
                ],
                "unique_together": {("user", "chat_room")},
            },
        ),
    ]
