# .github/workflows/CICD.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DB_NAME }}
          MYSQL_USER: ${{ secrets.MYSQL_DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo ${{ secrets.LOCAL_ENV }}" >> .env
        echo ${{ secrets.STAGE_ENV }}" >> .env.prod

    - name: Run tests
      run: |
        python manage.py test --settings=golbang.settings.dev

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: stage
    needs: build  # build job이 성공적으로 완료된 후에 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo ${{ secrets.STAGE_ENV }}" >> .env.prod
         

      - name: List files in root directory (Check that the env file was created successfully)
        run: |
          ls -la

      - name: Create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            whoami
            mkdir -p /home/ubuntu/srv/ubuntu

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/srv/ubuntu/
          remote_host: ${{ secrets.REMOTE_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.REMOTE_SSH_KEY }}


      - name: executing remote ssh commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: 43.200.41.240
          username: ubuntu
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            whoami
            sh /home/ubuntu/srv/ubuntu/config/scripts/deploy.sh